<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Amazon</name>
   <tag></tag>
   <elementGuidId>43982198-bb8d-4732-81cd-c56dd87c9aa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-bb-logo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-bb-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a80c7f9-a1c7-4fd2-88b9-c731411d96e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-bb-logo</value>
      <webElementGuid>3cdc5e6c-2671-43d0-931b-bc0b23b4a4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ref=nav_bb_logo</value>
      <webElementGuid>a4b71e47-89ce-4672-b9b9-cd755947be0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amazon</value>
      <webElementGuid>c3f7392f-f3b7-45ce-9035-b0b303d8e165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-bb-logo&quot;)</value>
      <webElementGuid>980f992d-7eca-4510-bc60-3010b8787e79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-bb-logo']</value>
      <webElementGuid>9c910749-da6f-4a77-a072-c963dc50a257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-backup-backup']/div/div/a</value>
      <webElementGuid>13c6af7b-a5a1-472a-817b-1d4de8f75cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Amazon')]</value>
      <webElementGuid>0583c9f4-9d5e-4e01-a5df-ac5dbcc32077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ref=nav_bb_logo')]</value>
      <webElementGuid>6af0130c-f250-4640-a7e5-8a3ff82b31e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>c0082568-61a6-4fbd-ab7d-ac1cf4b9d6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-bb-logo' and @href = '/ref=nav_bb_logo' and (text() = 'Amazon' or . = 'Amazon')]</value>
      <webElementGuid>d9740e17-8a8c-490d-9579-495a6cb41a21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
