<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Amazon</name>
   <tag></tag>
   <elementGuidId>3463c143-9116-4856-9f75-b944be05c6a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-bb-logo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-bb-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ba8c4ee-c56f-43a7-9896-c644e065524c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-bb-logo</value>
      <webElementGuid>5ef58c87-ace6-4b68-8426-81938a7136a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ref=nav_bb_logo</value>
      <webElementGuid>17c3ad00-54ea-45b1-a1af-7870126726ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amazon</value>
      <webElementGuid>bb761e85-603f-4c52-af0b-6d29d37fa692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-bb-logo&quot;)</value>
      <webElementGuid>bdd79ff3-9bed-412c-a6b8-ef47e9720155</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-bb-logo']</value>
      <webElementGuid>faf081b6-0f8c-4fdc-b7c8-0213bccb51fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar-backup-backup']/div/div/a</value>
      <webElementGuid>45d4647f-3a10-47f8-b9e9-3005ec2c2fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Amazon')]</value>
      <webElementGuid>d10807b0-2d89-4525-97e1-ce90f65b3bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ref=nav_bb_logo')]</value>
      <webElementGuid>15d27d14-d81f-4741-971c-472f35170713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>25396b72-5ebe-4701-8a25-547043863efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-bb-logo' and @href = '/ref=nav_bb_logo' and (text() = 'Amazon' or . = 'Amazon')]</value>
      <webElementGuid>33039e50-b692-4c20-a9c7-4272d5112487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
